language: c

compiler: gcc

cache: apt

before_install:
    - sudo apt-get update -qq
    - sudo apt-get -qq install build-essential
    - sudo apt-get -qq install bison flex libgmp-dev libncurses-dev libmpc-dev libmpfr-dev texinfo xzip lzip
    - sudo apt-get -qq install gcc-arm-linux-gnueabihf
    - sudo apt-get -qq install g++-arm-linux-gnueabihf

script:
    - cd $HOME
    - sudo mkdir -p /opt/adapteva
    - sudo chown $USER:$USER /opt/adapteva
    - unset EPIPHANY_BUILD_HOME
    - mkdir buildroot
    - cd buildroot
    - git clone https://github.com/adapteva/epiphany-sdk sdk --branch 2014.11
    - ./sdk/build-epiphany-sdk.sh -c arm-linux-gnueabihf -C || tail /home/travis/buildroot/logs/2014.11-rc1/build-2014-11-03-1550.log
    # Build epiphany-examples repo, just as a proof of concept.
    - cd $HOME
    - git clone https://github.com/adapteva/epiphany-examples.git
    - cd epiphany-examples/scripts
    - ./build_all.sh
